# Configuration parameters for python-sync app for Creek.fm stations
destination_folder: "C:/audio"
station_url: "http://creek.fm/"
key: ""

# logging information
log_level: "DEBUG"
log_path: "."
log_name: "pysync"
